"""
Administration router — config, cache clear, audit, test trigger.
Matches the Administration section of the Monitoring APIs blueprint (4/4).
Reuses logs_db/alerts_db/traces_db from the other monitoring routers to
generate a real test entry in each, and feeds the shared audit_logs_db
so GET /monitoring/audit has real data.
"""

from datetime import datetime, timezone
from uuid import uuid4

from fastapi import APIRouter, Depends

from app.schemas.monitoring_admin import (
    MonitoringConfigResponse,
    MonitoringConfigUpdateRequest,
    CacheClearResponse,
    MonitoringAuditEntry,
    MonitoringTestResponse,
)
from app.routers.monitoring_logs import logs_db
from app.routers.monitoring_alerts import alerts_db, _log_status_change
from app.routers.monitoring_tracing import traces_db
from app.models.user import audit_logs_db
from app.core.security import get_current_user

router = APIRouter(prefix="/api/v1/monitoring", tags=["Monitoring Administration"])

_config = {
    "log_retention_days": 30,
    "alert_threshold_cpu_percent": 90.0,
    "tracing_sample_rate": 1.0,
}

MONITORING_ACTIONS = {"monitoring_config_update", "monitoring_cache_clear", "monitoring_test"}


def _log_monitoring_audit(actor_email: str, action: str):
    audit_logs_db.append(
        {"actor_email": actor_email, "action": action, "timestamp": datetime.now(timezone.utc)}
    )


@router.patch("/config", response_model=MonitoringConfigResponse)
def update_config(
    data: MonitoringConfigUpdateRequest,
    current_user: dict = Depends(get_current_user),
):
    if data.log_retention_days is not None:
        _config["log_retention_days"] = data.log_retention_days
    if data.alert_threshold_cpu_percent is not None:
        _config["alert_threshold_cpu_percent"] = data.alert_threshold_cpu_percent
    if data.tracing_sample_rate is not None:
        _config["tracing_sample_rate"] = data.tracing_sample_rate
    _log_monitoring_audit(current_user["email"], "monitoring_config_update")
    return _config


@router.post("/cache/clear", response_model=CacheClearResponse)
def clear_cache(current_user: dict = Depends(get_current_user)):
    # STUB: no real metrics cache exists in this in-memory setup;
    # simulates clearing one by returning a fixed count.
    _log_monitoring_audit(current_user["email"], "monitoring_cache_clear")
    return CacheClearResponse(cleared_entries=12)


@router.get("/audit", response_model=list[MonitoringAuditEntry])
def get_monitoring_audit(current_user: dict = Depends(get_current_user)):
    entries = [e for e in audit_logs_db if e["action"] in MONITORING_ACTIONS]
    return sorted(entries, key=lambda e: e["timestamp"], reverse=True)


@router.post("/test", response_model=MonitoringTestResponse)
def trigger_test(current_user: dict = Depends(get_current_user)):
    now = datetime.now(timezone.utc)

    log_id = str(uuid4())
    logs_db[log_id] = {
        "id": log_id,
        "level": "info",
        "message": "Monitoring test triggered",
        "source": "app.routers.monitoring_admin",
        "timestamp": now,
    }

    alert_id = str(uuid4())
    alerts_db[alert_id] = {
        "id": alert_id,
        "title": "Test alert",
        "description": "Generated by POST /monitoring/test",
        "severity": "info",
        "status": "active",
        "created_at": now,
        "updated_at": now,
    }
    _log_status_change(alert_id, "active")

    trace_id = str(uuid4())
    traces_db[trace_id] = {
        "id": trace_id,
        "name": "POST /api/v1/monitoring/test",
        "status": "ok",
        "duration_ms": 1.2,
        "started_at": now,
    }

    _log_monitoring_audit(current_user["email"], "monitoring_test")

    return MonitoringTestResponse(
        log_id=log_id,
        alert_id=alert_id,
        trace_id=trace_id,
        detail="Test log, alert, and trace generated successfully",
    )