"""
Prompt Testing & Evaluation router — test, benchmark, evaluate, results,
abtest, score, metrics, regression.
Matches the Testing & Evaluation section of the Prompt Management APIs
blueprint (8/8).

IMPORTANT — READ BEFORE RELYING ON ANY RESULT FROM THIS ROUTER:
There is no real LLM call anywhere here. "Output" is generated by naive
Python str.format() substitution of {variables} into the prompt's stored
content (falling back to the raw content if formatting fails) — not a
model completion. "Score" and "similarity" are deterministic placeholder
heuristics (text length, difflib.SequenceMatcher ratio) — not a real
quality judgment. This is enough to exercise the API surface end-to-end
(request/response shapes, storage, aggregation) but NOT enough to actually
test or evaluate prompt quality. Wire in a real model call + real scoring
before using this for anything beyond API-contract testing.

Operates on prompts_db from prompts.py (Prompt CRUD router) — imported,
not duplicated. Every endpoint here requires the caller to own the
prompt(s) referenced, via prompts.py's existing _require_owner.

No route-ordering concerns: every path here (/prompt-test,
/prompt-benchmark, /prompt-evaluate, /prompt-results, /prompt-abtest,
/prompt-score, /prompt-metrics, /prompt-regression) is a flat, distinct,
top-level name under /api/v1 — none of them share a prefix with
prompts.router's /api/v1/prompts/{id}, so nothing can be swallowed by a
catch-all here.
"""

from datetime import datetime, timezone
from difflib import SequenceMatcher
from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException, Query

from app.schemas.prompt_testing import (
    PromptTestRequest,
    PromptTestResult,
    PromptBenchmarkRequest,
    PromptBenchmarkResult,
    PromptEvaluateRequest,
    PromptEvaluateResult,
    PromptResultSummary,
    PromptAbTestRequest,
    PromptAbTestResult,
    PromptScoreRequest,
    PromptScoreResult,
    PromptMetricsResponse,
    PromptRegressionRequest,
    PromptRegressionResult,
)
from app.routers.prompts import prompts_db, _get_prompt_or_404, _require_owner
from app.core.security import get_current_user

router = APIRouter(prefix="/api/v1", tags=["Prompt Testing & Evaluation"])

# result_id -> {..., "owner_email": str, "type": str, "created_at": datetime, ...}
prompt_results_db: dict[str, dict] = {}


def _simulate_output(prompt: dict, variables: dict) -> str:
    """Naive, non-LLM stand-in for a real model call — see module docstring."""
    content = prompt["content"]
    try:
        return content.format(**variables)
    except (KeyError, IndexError):
        return content


def _stub_score(text: str) -> float:
    """Deterministic placeholder score — NOT a real quality judgment."""
    return round(min(100.0, len(text.strip()) * 2.0), 2)


def _stub_latency_ms(text: str) -> float:
    return round(50.0 + len(text) * 0.1, 2)


def _similarity(a: str, b: str) -> float:
    return round(SequenceMatcher(None, a, b).ratio() * 100, 2)


def _record_result(result_id: str, prompt_id: str, owner_email: str, rtype: str, summary: str, now: datetime):
    prompt_results_db[result_id] = {
        "id": result_id,
        "prompt_id": prompt_id,
        "owner_email": owner_email,
        "type": rtype,
        "summary": summary,
        "created_at": now,
    }


@router.post("/prompt-test", response_model=PromptTestResult, status_code=201)
def prompt_test(
    data: PromptTestRequest,
    current_user: dict = Depends(get_current_user),
):
    prompt = _get_prompt_or_404(data.prompt_id)
    _require_owner(prompt, current_user["email"])
    output = _simulate_output(prompt, data.input_variables)
    now = datetime.now(timezone.utc)
    result_id = str(uuid4())
    passed = len(output.strip()) > 0
    _record_result(result_id, data.prompt_id, current_user["email"], "test", f"output_len={len(output)}", now)
    return PromptTestResult(
        id=result_id, prompt_id=data.prompt_id, output=output,
        passed=passed, latency_ms=_stub_latency_ms(output), created_at=now,
    )


@router.post("/prompt-benchmark", response_model=PromptBenchmarkResult, status_code=201)
def prompt_benchmark(
    data: PromptBenchmarkRequest,
    current_user: dict = Depends(get_current_user),
):
    prompt = _get_prompt_or_404(data.prompt_id)
    _require_owner(prompt, current_user["email"])
    now = datetime.now(timezone.utc)
    passed_count = 0
    latencies = []
    for case in data.test_cases:
        output = _simulate_output(prompt, case.input)
        latencies.append(_stub_latency_ms(output))
        if case.expected_output is None or output.strip() == case.expected_output.strip():
            passed_count += 1
    total = len(data.test_cases)
    avg_latency = round(sum(latencies) / total, 2) if total else 0.0
    result_id = str(uuid4())
    _record_result(
        result_id, data.prompt_id, current_user["email"], "benchmark",
        f"{passed_count}/{total} passed", now,
    )
    return PromptBenchmarkResult(
        id=result_id, prompt_id=data.prompt_id, total_cases=total,
        passed_count=passed_count, avg_latency_ms=avg_latency, created_at=now,
    )


@router.post("/prompt-evaluate", response_model=PromptEvaluateResult, status_code=201)
def prompt_evaluate(
    data: PromptEvaluateRequest,
    current_user: dict = Depends(get_current_user),
):
    prompt = _get_prompt_or_404(data.prompt_id)
    _require_owner(prompt, current_user["email"])
    now = datetime.now(timezone.utc)
    score = _stub_score(data.output_text)
    feedback = (
        f"Stub evaluation against {len(data.criteria)} criteria — "
        f"placeholder score based on output length only."
    )
    result_id = str(uuid4())
    _record_result(result_id, data.prompt_id, current_user["email"], "evaluate", f"score={score}", now)
    return PromptEvaluateResult(
        id=result_id, prompt_id=data.prompt_id, score=score, feedback=feedback, created_at=now,
    )


@router.get("/prompt-results", response_model=list[PromptResultSummary])
def prompt_results(
    prompt_id: str | None = Query(default=None),
    current_user: dict = Depends(get_current_user),
):
    results = [
        r for r in prompt_results_db.values()
        if r["owner_email"] == current_user["email"]
        and (prompt_id is None or r["prompt_id"] == prompt_id)
    ]
    results.sort(key=lambda r: r["created_at"], reverse=True)
    return [PromptResultSummary(**r) for r in results]


@router.post("/prompt-abtest", response_model=PromptAbTestResult, status_code=201)
def prompt_abtest(
    data: PromptAbTestRequest,
    current_user: dict = Depends(get_current_user),
):
    prompt_a = _get_prompt_or_404(data.prompt_id_a)
    prompt_b = _get_prompt_or_404(data.prompt_id_b)
    _require_owner(prompt_a, current_user["email"])
    _require_owner(prompt_b, current_user["email"])

    now = datetime.now(timezone.utc)
    outputs_a = [_simulate_output(prompt_a, c.input) for c in data.test_cases]
    outputs_b = [_simulate_output(prompt_b, c.input) for c in data.test_cases]
    score_a = round(sum(_stub_score(o) for o in outputs_a) / len(outputs_a), 2) if outputs_a else 0.0
    score_b = round(sum(_stub_score(o) for o in outputs_b) / len(outputs_b), 2) if outputs_b else 0.0

    if score_a > score_b:
        winner = "a"
    elif score_b > score_a:
        winner = "b"
    else:
        winner = "tie"

    result_id = str(uuid4())
    _record_result(
        result_id, data.prompt_id_a, current_user["email"], "abtest",
        f"winner={winner} ({score_a} vs {score_b})", now,
    )
    return PromptAbTestResult(
        id=result_id, prompt_id_a=data.prompt_id_a, prompt_id_b=data.prompt_id_b,
        winner=winner, score_a=score_a, score_b=score_b, created_at=now,
    )


@router.post("/prompt-score", response_model=PromptScoreResult, status_code=201)
def prompt_score(
    data: PromptScoreRequest,
    current_user: dict = Depends(get_current_user),
):
    prompt = _get_prompt_or_404(data.prompt_id)
    _require_owner(prompt, current_user["email"])
    now = datetime.now(timezone.utc)
    score = _stub_score(data.output_text)
    breakdown = {
        "length_score": score,
        "non_empty": 100.0 if data.output_text.strip() else 0.0,
    }
    result_id = str(uuid4())
    _record_result(result_id, data.prompt_id, current_user["email"], "score", f"score={score}", now)
    return PromptScoreResult(
        id=result_id, prompt_id=data.prompt_id, score=score, breakdown=breakdown, created_at=now,
    )


@router.get("/prompt-metrics", response_model=PromptMetricsResponse)
def prompt_metrics(current_user: dict = Depends(get_current_user)):
    owned = [r for r in prompt_results_db.values() if r["owner_email"] == current_user["email"]]
    counts = {t: 0 for t in ("test", "benchmark", "evaluate", "abtest", "score", "regression")}
    for r in owned:
        counts[r["type"]] = counts.get(r["type"], 0) + 1

    scores = []
    for r in owned:
        if r["type"] in ("evaluate", "score") and "score=" in r["summary"]:
            try:
                scores.append(float(r["summary"].split("score=")[1]))
            except ValueError:
                pass
    avg_score = round(sum(scores) / len(scores), 2) if scores else 0.0

    return PromptMetricsResponse(
        total_tests=counts["test"],
        total_benchmarks=counts["benchmark"],
        total_evaluations=counts["evaluate"],
        total_abtests=counts["abtest"],
        total_scores=counts["score"],
        total_regressions=counts["regression"],
        avg_score=avg_score,
    )


@router.post("/prompt-regression", response_model=PromptRegressionResult, status_code=201)
def prompt_regression(
    data: PromptRegressionRequest,
    current_user: dict = Depends(get_current_user),
):
    prompt = _get_prompt_or_404(data.prompt_id)
    _require_owner(prompt, current_user["email"])
    now = datetime.now(timezone.utc)
    similarity = _similarity(data.baseline_output, data.current_output)
    # Arbitrary but documented threshold — outputs less than 70% similar are
    # flagged as a potential regression. Tune this for your real use case.
    regression_detected = similarity < 70.0
    result_id = str(uuid4())
    _record_result(
        result_id, data.prompt_id, current_user["email"], "regression",
        f"similarity={similarity}", now,
    )
    return PromptRegressionResult(
        id=result_id, prompt_id=data.prompt_id,
        regression_detected=regression_detected, similarity=similarity, created_at=now,
    )